version: '3.8'

services:
  app:
    image: ${IMAGE_TAG:-ghcr.io/creedxyz/safe-watcher:latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Creed-SafeWatcher
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - SAFE_ADDRESSES=${SAFE_ADDRESSES}
      - SIGNERS=${SIGNERS}
      - SAFE_URL=${SAFE_URL:-https://app.safe.global}
      - POLL_INTERVAL=${POLL_INTERVAL:-20}
      - API=${API:-fallback}